spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.215/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://172.20.10.10/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
wechat:
  mpAppId: wx234b65348218b500
  mpAppSecret: 6d34d263f10fa89ec927320b146aee06